modLoader="javafml"
loaderVersion="[2,)"
license="Academic Free License v3.0"

[[mods]]
modId="better_tools"
version="11.0.1"
displayName="Better Tools and Armor"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-tools-and-armor"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="BlackCatGamer64, MCreator"
description="Adds many new ores and resources which improve the progression and exploration in Minecraft. Also adds many misc. features"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.better_tools]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_tools]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_tools]]
    modId="curios"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_tools]]
    modId="jei"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_tools]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_tools]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

